export type AcademicReportSubject = {
  subject: string;
  score: number;
  total: number;
  grade: string;
  remarks: string;
};

export type AcademicReportPayload = {
  schoolName: string;
  studentName: string;
  examName: string;
  generatedAt: string;
  subjects: AcademicReportSubject[];
};

export function downloadAcademicReportPdf(payload: AcademicReportPayload) {
  const average = Math.round(
    payload.subjects.reduce((sum, subject) => sum + subject.score, 0) / Math.max(payload.subjects.length, 1),
  );

  const lines = [
    payload.schoolName,
    "Academic Report",
    `Student: ${payload.studentName}`,
    `Exam: ${payload.examName}`,
    `Generated: ${payload.generatedAt}`,
    `Overall Average: ${average}%`,
    "",
    "Subject Results",
    ...payload.subjects.flatMap((subject) => [
      `${subject.subject}: ${subject.score}/${subject.total} - Grade ${subject.grade}`,
      `Remark: ${subject.remarks}`,
      "",
    ]),
    "This report is generated by Ocean Education Platform.",
  ];

  const pdf = buildSimplePdf(lines);
  const blob = new Blob([pdf], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${payload.studentName.replace(/\s+/g, "-").toLowerCase()}-${payload.examName.replace(/\s+/g, "-").toLowerCase()}-report.pdf`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

function buildSimplePdf(lines: string[]) {
  const safeLines = lines.map((line) => escapePdfText(line));
  const content = [
    "BT",
    "/F1 18 Tf",
    "50 790 Td",
    `(${safeLines[0] ?? "Ocean Education"}) Tj`,
    "/F1 13 Tf",
    ...safeLines.slice(1).flatMap((line) => ["0 -22 Td", `(${line}) Tj`]),
    "ET",
  ].join("\n");

  const objects = [
    "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
    "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n",
    `4 0 obj\n<< /Length ${content.length} >>\nstream\n${content}\nendstream\nendobj\n`,
    "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];

  for (const object of objects) {
    offsets.push(pdf.length);
    pdf += object;
  }

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (const offset of offsets.slice(1)) {
    pdf += `${offset.toString().padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return pdf;
}

function escapePdfText(value: string) {
  return value
    .replace(/[^\x20-\x7E]/g, "")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}
